### ISSUE TITLE
Pensar e criar rotas do sistema. Etapa final, pensando no desenvolvimento.

### ISSUE THREAD

**Issue by Gessilt** [Gessilt/Socrates#8]
- [x] Pensar nas rotas; 
- [ ] Implementação.

**Comment by Gessilt** [comment]
# Em desenvolvimento...
## Rotas 

- Login;

- Cadastro;

- Home;

- Configurações;

- Calendário para tarefas e exames;
  - Modal para mostrar as tarefas e exames do dia selecionado;
  - Ao clicar, leva para a tarefa e exame específico;
  - Botão para criar tarefa e exame.
  
- Criação da tarefa

- Criação do exame

- Tarefa específica;
  - Editar e apagar em um modal.
  
- Exame específico;
   - Editar e apagar em um modal. 
   
- Anotações;
   - Várias anotações;
   - Botão para criar.

- Criação da anotação

- Anotação específica;
  - Editar e apagar em um modal.
  
- Pergaminhos;
    - Botão para criar um tomo.

- Criação do tomo

- Tomo específico;
   - Botão para criar uma escrita. 

- Criação da escrita;

-

-

-

-

**Comment by Gessilt** [comment]
Acredito que são essas, mesmo. @edigar ?

**Comment by edigar** [comment]
Você não precisa definir todas agora. Esse tanto já vai dar um bom trabalho e depois vamos pivotando, se houver necessidade.
